create or replace PROCEDURE      INSERE_PROJETO
(I_ID IN BRH.PROJETO.ID%TYPE,
 I_NOME IN BRH.PROJETO.NOME%TYPE,
 I_RESPONSAVEL IN BRH.PROJETO.RESPONSAVEL%TYPE,
 I_INICIO DATE,
 I_FIM DATE)
 IS 
 BEGIN
    INSERT INTO BRH.PROJETO
        (ID, NOME, RESPONSAVEL, INICIO, FIM)
    VALUES 
        (I_ID, I_NOME, I_RESPONSAVEL, I_INICIO, I_FIM);
 END;



----------------------------------------------------------------------------------

create or replace FUNCTION     CALCULA_IDADE 
(C_DATA_CALC IN DATE)
RETURN FLOAT
IS
    A_IDADE FLOAT;
BEGIN
    A_IDADE := FLOOR(MONTHS_BETWEEN(SYSDATE, C_DATA_CALC) / 12);
    RETURN A_IDADE;
END;